server:
  port: 8181
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    username: root
    password: root
  profiles:
    active: devy
  #设置返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #添加默认时间格式，不加的话，从数据库取出来格式为：2019-10-30T06:18:46.000+00:00
    time-zone: GMT+8 #添加时区
#mybatis 日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl